### ISSUE TITLE
Add a `Local` property to `JinagaClient`

### ISSUE THREAD

**Issue by zeldafreak** [jinaga/jinaga.net#93]
Add a `Local` (or perhaps `LocalClient`) property to `JinagaClient` which returns a new client that performs all operations except `Subscribe` (e.g. `Query`, `Fact`, `Watch`) locally.

`JinagaClient.Local.Fact` would put the fact into local storage, but that fact would not be pushed to the replicator unless it was added to the connected client, or was a predecessor to fact added to the connected client.

`JinagaClient.Local.Query` would be equivalent to `QueryLocal` today.

`JinagaClient.Local.Watch` would only notify observers when facts were added to the local store.

`JinagaClient.QueryLocal` would receive the `ObsoleteAttribute` and redirected to `JinagaClient.Local.Query`. It could then be removed in the next major version increment.

## Motivation

An application may have device-specific, local state it would like to persist to its local Jinaga store, but doesn't want to send to the replicator or other clients of the replicator. This would require a `FactLocal`. 

The same application might want to `Watch` for changes to those local facts, so a `WatchLocal` would also be useful.

When every action the client can take has a `-Local` equivalent, it makes some sense to simply have a separate instance that doesn't know about the replicator. This would also allow developers to write components that are agnostic as to whether they are working locally or connected to a replicator-- that decision could be made by an ancestor in the component hierarchy or by DI/IoC.

**Comment by michaellperry** [comment]
@zeldafreak Please review PR #101

**Comment by michaellperry** [comment]
Completed with PR #107
